name: Release Workflow
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version number'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git config --global credential.helper store

      - name: Authenticate with GitHub Token
        env:
          GITHUB_TOKEN: ${{ secrets.TECH_USER_TOKEN }}
        run: |
          git remote set-url origin https://${{ secrets.TECH_USER_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Merge master into release
        run: |
          git checkout release
          git merge origin/master

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # See https://github.com/actions/setup-java for options
          java-version: '21'       # Specify the Java version you need

      - name: Update version
        run: |
          mvn versions:set -DnewVersion=${{ github.event.inputs.version }}
          mvn versions:commit

      - name: Commit version
        run: |
          git add .
          git commit -m "Bump version to ${{ github.event.inputs.version }}"

      - name: Push changes to release branch
        run: |
          git push origin release

      - name: Merge release into master
        run: |
          git checkout master
          git merge release

      - name: Push changes to master branch
        run: |
          git push origin master
