name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'VERSION'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TECH_USER_TOKEN }}

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Configure Git for GitHub Actions
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Check out the release branch
        run: |
          version=${{ github.event.inputs.version }}
          git checkout -b release origin/release || git checkout release

      - name: Merge master into release branch
        run: |
          version=${{ github.event.inputs.version }}
          git fetch
          git checkout release
          git merge origin/master

      - name: Update Maven version
        run: |
          mvn versions:set -DnewVersion=${{ github.event.inputs.version }}
          git add pom.xml
          git commit -m "Set version to ${{ github.event.inputs.version }}"

      - name: Push changes to release branch
        run: |
          git push https://x-access-token:${{ secrets.TECH_USER_TOKEN }}@github.com/${{ github.repository }} release/${{ github.event.inputs.version }}

      - name: Merge release branch into master
        run: |
          git checkout master
          git merge release/${{ github.event.inputs.version }}
          git push https://x-access-token:${{ secrets.TECH_USER_TOKEN }}@github.com/${{ github.repository }} master

      - name: Create a new tag
        run: |
          git tag -a v${{ github.event.inputs.version }} -m "Release version ${{ github.event.inputs.version }}"
          git push https://x-access-token:${{ secrets.TECH_USER_TOKEN }}@github.com/${{ github.repository }} v${{ github.event.inputs.version }}